SAMPLE=$1

ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.aligned.final.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.aligned.final.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.aligned.pulled.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.aligned.pulled.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.tmp.bed
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.hum_breaks.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.ALU.hum_breaks.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.aligned.final.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.aligned.final.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.aligned.pulled.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.aligned.pulled.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.hum_breaks.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.hum_breaks.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.LINE1.tmp.bed
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.aligned.final.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.aligned.final.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.aligned.pulled.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.aligned.pulled.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.hum_breaks.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.hum_breaks.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.HERVK.tmp.bed
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.aligned.final.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.aligned.final.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.aligned.pulled.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.aligned.pulled.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.hum_breaks.sorted.bam
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.hum_breaks.sorted.bam.bai
ln -s ../$SAMPLE/$SAMPLE/$SAMPLE.SVA.tmp.bed
ln -s ../$SAMPLE/$SAMPLE/${SAMPLE}tmp
